### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by shff** [orby-js/core#2]
Hi, Matias!

Just some feedback: I've been using Orby for an internal SPA app at work and it works incredibly well. I haven't come across any issue at all, even when using Parcel's experimental compilation features and inlining everything into a single HTML file.

I'll be a speaker tomorrow at a local conf and I'll make sure I mention Orby and Preact as my favorite frameworks to use in 2019.

Let me know if there's anything I can help with! It feels complete to me, but I'd love to contribute to your project!

**Comment by UpperCod** [comment]
thanks for your feedback, a great change is approaching, I will merge Orby and Atomico, this is to focus my efforts on promoting a single library, with the same objectives, the current api will not have major changes in its use, but if the core is rewritten , be it in the handling of high order components, microtareas and more.

I share a look at the future of fusion. 

```jsx
import { h, useEffect } from "@atomico/core";
import { register } from "@atomico/web-component";

function MyTag(props){
    useEffect(()=>{
        console.log("component mounted")
        return ()=>console.log("component unmount");
    },[])
    return <host useShadowDom>
        <style>{`:host{width:100px;height:100px}`}</style>
        <h1>my web-component</h1>	
    </host>
}

register(<my-tag>{MyTag}</my-tag>)
```

I hope these changes do not discourage the use of fusion, in fact I would like to inform you more about it, [Atomico](https://github.com/atomicojs/core)

**Comment by shff** [comment]
Hi @UpperCod !!! This sounds amazing. WebComponent support and ShadowDom sure look extremely interesting.

I didn't know about Atomico, but I'll follow the repo and make sure I try it it out in the following weeks! 😃
